# Generated by Django 5.2.16 on 2026-08-14 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_phase_2_accounts'),
        ('books', '0003_bookcopy_availability_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Minat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('accepted', 'Diterima'), ('rejected', 'Ditolak'), ('withdrawn', 'Dibatalkan'), ('automatically_rejected', 'Ditolak otomatis')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('offered_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offered_in_minat', to='books.bookcopy')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_minat', to=settings.AUTH_USER_MODEL)),
                ('requested_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_in_minat', to='books.bookcopy')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_minat', to=settings.AUTH_USER_MODEL)),
                ('swap_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minat', to='accounts.swapzone')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='BookSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('coordinating', 'Koordinasi')], default='coordinating', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('swap_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_swaps', to='accounts.swapzone')),
                ('minat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='book_swap', to='swaps.minat')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='minat',
            constraint=models.CheckConstraint(condition=models.Q(('requested_copy', models.F('offered_copy')), _negated=True), name='swaps_minat_distinct_copies'),
        ),
        migrations.AddConstraint(
            model_name='minat',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requester', 'requested_copy', 'offered_copy', 'swap_zone'), name='swaps_minat_unique_pending_combination'),
        ),
    ]
