# Generated by Django 5.2.16 on 2026-08-02 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=500)),
                ('isbn', models.CharField(blank=True, max_length=17, null=True)),
                ('language', models.CharField(max_length=100)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title', 'authors', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('isbn__isnull', False)), fields=('isbn',), name='books_book_isbn_unique'), models.CheckConstraint(condition=models.Q(('isbn__isnull', True), models.Q(('isbn', ''), _negated=True), _connector='OR'), name='books_book_isbn_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('like_new', 'Seperti Baru'), ('very_good', 'Sangat Bagus'), ('good', 'Masih Bagus'), ('fair', 'Cukup Bagus'), ('bad', 'Sudah Buruk')], max_length=20)),
                ('condition_note', models.CharField(blank=True, max_length=140)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='books.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_copies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('condition__in', ['like_new', 'very_good', 'good', 'fair', 'bad'])), name='books_bookcopy_condition_valid')],
            },
        ),
    ]
